# -*- coding: utf-8 -*-
"""pytorch_resnet50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CJFlyGTALSJpdBNSio0v3fyVq28Eyqp0
"""
##1단계 ResNet (Residual Network), 잔차신경망 (ResNet) 어떤 모형에서 예측값과 실측값의 차이로 생기는 부분에 대한 느낌이나 생각의 짜임새의 뜻을 나타내는 말
# 📝 torch는 PyTorch의 기본 도구
import torch

# 📝 nn은 신경망 레이어를 만들 때 사용함
import torch.nn as nn

# 📝 optim은 모델의 가중치를 업데이트할 때 사용함
import torch.optim as optim

# 📝 DataLoader는 데이터를 batch 단위로 나눠서 모델에 넣어줌
# 📝 TensorDataset은 입력 데이터 x와 정답 y를 하나로 묶어줌
from torch.utils.data import DataLoader, TensorDataset

# 📝 numpy는 숫자 데이터를 만들고 다룰 때 사용함
import numpy as np

# 📝 torchvision.models에는 ResNet 같은 이미지 모델이 들어있음
from torchvision import models

# 📝 분류할 클래스 개수
# 📝 예: 10이면 정답 종류가 10개라는 뜻
num_classes = 10

# 📝 이미지 한 장의 모양
# 📝 3은 RGB 채널, 224x224는 이미지 크기
input_shape = (3, 224, 224)

# 📝 학습용 가짜 이미지 데이터 1000개를 만듦
# 📝 (1000, 3, 224, 224) = 이미지 1000장, RGB 3채널, 224x224 크기
# ⚠️ 실제 이미지 파일을 불러온 것이 아니라 랜덤 숫자로 만든 데이터임
x_train = np.random.random((1000, 3, 224, 224)).astype(np.float32)
# 📝 학습용 정답 라벨 1000개를 만듦
# 📝 num_classes가 10이므로 0부터 9까지 숫자 중 하나가 정답이 됨
y_train = np.random.randint(num_classes, size=(1000,))

# 📝 테스트용 가짜 이미지 데이터 200개를 만듦
x_test = np.random.random((200, 3, 224, 224)).astype(np.float32)

# 📝 테스트용 정답 라벨 200개를 만듦
y_test = np.random.randint(num_classes, size=(200,))

# 📝 numpy 데이터를 torch tensor로 바꾼 뒤 입력 x와 정답 y를 묶음
train_dataset = TensorDataset(torch.tensor(x_train), torch.tensor(y_train))

# 📝 테스트 데이터도 같은 방식으로 묶음
test_dataset = TensorDataset(torch.tensor(x_test), torch.tensor(y_test))

# 📝 batch_size=32는 데이터를 32개씩 나눠서 학습한다는 뜻
# 📝 shuffle=True는 학습 데이터를 섞어서 학습한다는 뜻
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

# 📝 테스트는 보통 순서가 크게 중요하지 않아서 shuffle=False를 사용함
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

base_model = models.resnet50(weights=None)
base_model = nn.Sequential(*list(base_model.children())[:-2])  # GlobalAveragePooling을 위해 마지막 두 레이어를 제거

class CustomResNet50(nn.Module):
    def __init__(self, num_classes):
        super(CustomResNet50, self).__init__()
        self.base_model = base_model
        self.global_avg_pool = nn.AdaptiveAvgPool2d((1, 1))
        self.fc1 = nn.Linear(2048, 256)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(256, num_classes)
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        x = self.base_model(x)
        x = self.global_avg_pool(x)
        x = torch.flatten(x, 1)
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.softmax(x)
        return x

model = CustomResNet50(num_classes=num_classes)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.0001)

num_epochs = 10

for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0
    for inputs, labels in train_loader:
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    print(f'Epoch {epoch+1}, Loss: {running_loss/len(train_loader)}')

model.eval()
correct = 0
total = 0
with torch.no_grad():
    for inputs, labels in test_loader:
        outputs = model(inputs)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

accuracy = correct / total
print(f'Test Accuracy: {accuracy * 100:.2f}%')